import vertica_python
import json

conn_info = {'host': '172.20.250.7',
             'port': 5433,
             'user': 'bigdata',
             'password': 'bigdata123',
             'database': 'km',
             # autogenerated session label by default,
             'session_label': 'some_label',
             # default throw error on invalid UTF-8 results
             'unicode_error': 'strict',
             # SSL is disabled by default
             'ssl': False,
             # using server-side prepared statements is disabled by default
             'use_prepared_statements': False,
             # connection timeout is not enabled by default
             'connection_timeout': 5}


def get_data_json(rows, page):
    connection = vertica_python.connect(**conn_info)
    cur = connection.cursor()
    page = int(rows) * (int(page)-1)
    sql = """ SELECT shopcode,shopname,shopid,address,branch from km_dws.dws_dim_shop order by shopid limit {} offset {}""".format(rows, page)
    cur.execute(sql)

    jsonData = []
    for row in cur.iterate():
        result = {"shopcode": row[0], "shopname": row[1], "shopid": row[2], "address": str(row[3]), "branch": str(row[4])}
        jsonData.append(result)
    connection.close()
    return jsonData

def get_data_total():
    connection = vertica_python.connect(**conn_info)
    cur = connection.cursor()
    sql = """ SELECT count(1) total from km_dws.dws_dim_shop """
    cur.execute(sql)
    for row in cur.iterate():
        total = row[0]
    connection.close()
    return total